### ISSUE TITLE
Error when installing NSP?

### ISSUE THREAD

**Issue by abiem** [developersu/ns-usbloader#43]
Hi not sure if this is the right place but it's wrecking my brain and I need help:
- Recently installed latest Atmosphere 0.10 on my Switch and was on fw9.1
- on Goldleaf 0.8
- on MacOS (Catalina) using ns-usbloader1.0
- when I try to install my nsp I keep getting errors like attached screenshot
- I'm sure the nsp's work because I got it from a friend who has successfully installed it and played on his end (but he uses windows machine and tinfoil)
- I tried to install tinfoil on my switch, and upon launching it on the switch it doesn't seem to do anything it just freezes (I assume because it's outdated and can't work with the latest cfw?)

Any idea what I should do or is missing? thank you!

![IMG_7941](https://user-images.githubusercontent.com/1831925/73524461-03853780-43c2-11ea-92bc-8dfd63fbe016.jpg)
![IMG_7940](https://user-images.githubusercontent.com/1831925/73524462-03853780-43c2-11ea-9f96-1c9ecd43affb.jpg)

**Comment by developersu** [comment]
Hi Allen,

You have to have sigpatches ('fs' and 'es') installed on your NS to solve this issue. 
Grab it from here: https://github.com/Joonie86/hekate/releases

Hope it helps. I use them with [Kosmos CFW](https://github.com/AtlasNX/Kosmos/releases) but I guess it should be working for you too, since this CFW is based on Atmosphere.

**Comment by abiem** [comment]
thank you!! but I must be an idiot..the instruction says to extract the zip and put them in SD root that's all, I tried that (and even manually copied the folders inside to the same folders in atmosphere) and still get the install error : ( Any idea why? 

The last line of instructions say: In order to use "nocmac patches", please add "kip1patch=nocmac" in hekate_ipl.ini

Do I need to do that at all?

https://sdsetup.com <<< This is where I prep'd my SD card, seems pretty standard?

<img width="850" alt="image" src="https://user-images.githubusercontent.com/1831925/73560370-a44c1500-440b-11ea-89b0-09e25bb5c960.png">

**Comment by developersu** [comment]
You need to get 'Kosmos_patches_12_08_2019.zip' and unpack it to your SD root AS IS, so you'll have 'patches.ini' file in 'sd:/bootloader' folder and 'exefs_patches' in 'sd:/atmosphere' folder.

Also I recommend you to read this [guide](https://switch.homebrew.guide/). I'm not a big expert in using 'Atmosphere' without any CFW around it, so I just use Kosmos (there are a lot of things pre-set to not burn fuses and taking care of GC and other non-trivial checks that saves NS). 
Soo.. really, I don't know much. I just download everything already prepared, remove what I don't need and install what I do ([Awoo Installer](https://github.com/Huntereb/Awoo-Installer/), for example) and somehow it works. To get GoldLeaf working you have to have this sigpatches (whatever they are) and.. this is it =)

About this last line: I don't know.. take the 'hekate_ipl.ini' from Kosmos and look what they did.. I mean they did it right. I didn't change anything in there. It's just works for me. It's in case if you want to clarify this and do not look for easy solutions :P

https://sdsetup.com is a good site but I didn't use it (yes, I'm really dumb and don't wanna to go deep). I used to download the latest Kosmos from here: https://github.com/AtlasNX/Kosmos/releases. File called 'Kosmos-v15.zip' (actual for the moment). Just unpack what you see into your SD card and (then unpack sigpatches taken from that.. another place) this is it!

**Comment by abiem** [comment]
Got it thank you it worked!!! I was taking it too literally and really just shoved the unzipped "Kosmos_patches_12_08_2019" folder into root folder... But I got smarter and copied the contents of that folder to the root level and merged with existing stuff and it works now!! thank you thank you!!

**Comment by developersu** [comment]
You're welcome :)
